{% set name = "GLM" %}
{% set version = "0.9.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/g-truc/glm/releases/download/{{ version }}/glm-{{ version }}.zip
  sha256: 8ec5069b61da07bdaf7098881ff0628c4cf7c3a42292f5a27e35aa9e1502dd17

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -r "${PREFIX}/include/glm"  # [unix]
    - if not exist %LIBRARY_INC%\glm exit 1  # [win]

about:
  home: https://glm.g-truc.net
  license: MIT
  license_family: MIT
  license_file: manual.md
  summary: OpenGL Mathematics
  dev_url: https://github.com/g-truc/glm

extra:
  recipe-maintainers:
    - mcs07
