{% set name = "GLM" %}
{% set version = "0.9.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/g-truc/glm/releases/download/{{ version }}/glm-{{ version }}.zip
  sha256: 496e855590b8aa138347429b7fc745d66707303fb82c1545260d1888472e137b

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake

test:
  commands:
    - test -r "${PREFIX}/include/glm"  # [unix]
    - if not exist %LIBRARY_INC%\glm exit 1  # [win]

about:
  home: https://glm.g-truc.net
  license: MIT
  license_family: MIT
  license_file: manual.md
  summary: OpenGL Mathematics
  dev_url: https://github.com/g-truc/glm

extra:
  recipe-maintainers:
    - mcs07
