{% set name = "GLM" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/g-truc/glm/archive/refs/tags/{{ version }}.tar.gz

  # patches:
  #   - patches/macos_test_errors.patch
  #   - patches/cmake_install_target.patch

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -r "${PREFIX}/include/glm"  # [unix]
    - if not exist %LIBRARY_INC%\glm exit 1  # [win]

about:
  home: https://glm.g-truc.net
  license: MIT
  license_family: MIT
  license_file: manual.md
  summary: OpenGL Mathematics
  dev_url: https://github.com/g-truc/glm

extra:
  recipe-maintainers:
    - traversaro
