appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gAdlOUHUUMAp/Su6EzyF2Tfm59pbE8NCjnHOn3lEXKcYis6ohcwYgNngQfQTS7phonzPGAZ0tRUyoa/PMtdqMabW5L6w1Q1L24aidsDaAetgy9m8cCm4hytkwuPGfxFB3H+OHFZr4UaBU+9AzsyKcl4U6qTns9TZc3IIrS2aXIbrc1Yp1OiYUe1H9nVcE3pQjkRdjpJge89BVpLTFXFvypNA5ht6uqeYRGpsOrqnzKIr3UGs21/LKUClEu1osBE04Ctzq87yuXXOAzXymjgtJnRuqqlucvVZfG/CxPmvDI0Cjcm2b5NPUMmIeGtw3An+OcbPbRwjPsMTBa7SrZijZXK7v5qzDYOa4PGlMM4RzHjtldXYJfp1G4UU6JOF5q5PNlkXyyuS8gcYupXnavC5BIgJN4ICIEuRs1rDZWGDH8V3b0ILsPwiBGEOooAhMiYXb+9nBMFtmLnKjdnSQ+PmqLzPsKg6W8gHJDAi5l+k2vjByl81LWanZWqftURSoZJvLmI3Iib6lL/KrHY3SKLcxGbSq8qTMB3M80cwPe6IBaHq5WHpPJ1VR9zh1HVAYwCRoklCW1oRowEJX7rp7869JfoPBLR2ITEQGKfM9BPKHwsQHtXr8zPyhRVnCwnZkC1AwmtLNOfuQpFQUh6cHla9rZMzsa1J+7pirAcNoDZFdm0=}
